export default {
  "LOFT_INSULATION": "Loft Insulation",
  "LOFT_REPAIR":"Loft Repair",
  // boiler replacement is the same as boiler installation...
  "BOILER_INSTALLATION": "Boiler Installation",
  "BOILER_REPAIR": "Boiler Repair",
  "RADIATOR_INSTALLATION": "Radiator Installation",
  "RADIATOR_REPAIR": "Radiator Repair",
  // gas central heating is the same as boiler
  "HOT_WATER_CYLINDER_INSTALLATION": "Hot Water Cylinder Installation",
  "HOT_WATER_CYLINDER_REPAIR": "Hot Water Cylinder Repair",
  // idk what water pump is for but heat pump is way more important
  "HEAT_PUMP_INSTALLATION": "Heat Pump Installation",
  "HEAT_PUMP_REPAIR": "Heat Pump Repair",

  "AIR_HEATING": "Air Heating",
  // idk what the difference between a roof and a new roof is
  "FLAT_ROOF_INSULATION": "Flat Roof Insulation",
  "FLAT_ROOF_REPAIR": "Flat Roof Repair",
  "FLAT_ROOF_REPLACEMENT": "Flat Roof Replacement",
  "PITCHED_ROOF_INSULATION": "Pitched Roof Insulation",
  "PITCHED_ROOF_REPAIR": "Pitched Roof Repair",
  "PITCHED_ROOF_REPLACEMENT": "Pitched Roof Replacement",
  "CONSERVATORY_ROOF_INSULATION": "Conservatory Roof Insulation",
  "CONSERVATORY_ROOF_REPAIR": "Conservatory Roof Repair",
  "CONSERVATORY_ROOF_REPLACEMENT": "Conservatory Roof Replacement",
  "BALCONY_ROOF_INSULATION": "Balcony Roof Insulation",
  "BALCONY_ROOF_REPAIR": "Balcony Roof Repair",
  "BALCONY_ROOF_REPLACEMENT": "Balcony Roof Replacement",
  "DAMP_PROOFING": "Damp Proofing",
  "CHIMNEY_REPAIR": "Chimney Repair",
  "CHIMNEY_REPLACEMENT": "Chimney Replacement",
  "CHIMNEY_CLEANING": "Chimney Cleaning",
  "CHIMNEY_CAP": "Chimney Cap",
  "DOOR_INSTALLATION": "Door Installation",
  "DOOR_REPAIR": "Door Repair",
  "WINDOW_INSTALLATION": "Window Installation",
  "WINDOW_REPAIR": "Window Repair",
  "SKIRTING_INSTALLATION": "Skirting Installation",
  "EWI": "External Wall Insulation",
  "IWI": "Internal Wall Insulation",
  "FILLED_CAVITY": "Filled Cavity Wall Insulation",
  "ELECTRICIAN": "Electrician",
  "ELECTRIC_STORAGE_HEATERS": "Electric Storage Heaters",
  "ELECTRIC_VEHICLE_CHARGING": "Electric Vehicle Charging",
  "BUILDER": "Builder",
  "FLOORING_EXPERT": "Flooring Expert",
  "PLUMBER": "Plumber",
  "BATTERY_STORAGE": "Battery Storage",
  "MICRO_CHP": "Micro Chp",
  "SOLAR_PV": "Solar Pv",
  "SOLAR_THERMAL": "Solar Thermal",
  "WINDTURBINE": "Wind Turbine",
  "AIR_CONDITION_INSTALLATION": "Air Condition Installation",
  "AIR_CONDITION_REPAIR": "Air condition Repair"
};
