version: '3'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"
    networks:
      - app_net
    volumes:
      - ./:/app
    command: sh -c "npm install && npm start"

  backend:
    build:
      context: ./
      dockerfile: Dockerfile-backend
      args:
        MAVEN_OPTS: "-Dmaven.repo.local=/m2/repository"
    ports:
      - "8080:8080"
    networks:
      - app_net
    volumes:
      - ./:/app
      - m2_repository:/m2/repository
    command: sh -c "mvn clean && mvn spring-boot:run"

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: retrofit
    volumes:
      - ./data:/var/lib/mysql
      - ./retrofit.sql:/docker-entrypoint-initdb.d/retrofit.sql
    networks:
      - app_net
    ports:
      - "3306:3306"

volumes:
  m2_repository:

networks:
  app_net:
