retrofit:
  jwt:
    privateKeyPath: rsa\rsa-key
    expire: 120
  avatar: https://avatarspe.oss-cn-beijing.aliyuncs.com/2023/04/27/134f6nve7z6xshm91p2h9cyht5l2j0gny8a9zkx8dxck0zsftimg.jpg
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tQtrBkcA1dCcNJCPVwr
    accessKeySecret: E1U3vsL7VDb7Px2xrO7fMYCrNW6d1a
    protocol: https
    bucketName: avatarspe
    maxSize: 500
    envName: mac

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://docker_db_1:3306/retrofit
    username: root
    password: 123456
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: org.bristolenergynetwork.retrofit.model
  mapper-locations: classpath*:mapper/*Mapper.xml
